GigaReviewTest:
  variables:
    COMPOSE_FILE: docker-compose.yml
    REPO_NAME: $CI_PROJECT_NAME
    REVIEW_ENV: dev
    POSTGRES_MAJOR_VERSION: 12
    POSTGRES_DB: postgres
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: changeme
    GROUP_VARIABLES_URL: "https://gitlab.com/api/v4/groups/gigascience/variables?per_page=100"
    FORK_VARIABLES_URL: "https://gitlab.com/api/v4/groups/3501869/variables"
    PROJECT_VARIABLES_URL: "https://gitlab.com/api/v4/projects/gigascience%2Fforks%2F$REPO_NAME/variables"
    MISC_VARIABLES_URL: "https://gitlab.com/api/v4/projects/gigascience%2Fcnhk-infra/variables"
    GITLAB_PRIVATE_TOKEN: $CI_BUILD_TOKEN
  stage: test
  script:
    - cd gigareview
    - env | grep -iE "(REVIEW_ENV|REPO_NAME|POSTGRES_MAJOR_VERSION|POSTGRES_DB|POSTGRES_USER|POSTGRES_PASSWORD|GROUP_VARIABLES_URL|FORK_VARIABLES_URL|PROJECT_VARIABLES_URL|MISC_VARIABLES_URL|GITLAB_PRIVATE_TOKEN)"| tee .env
    - ./up.sh
    - "./tests/unit_runner && ./tests/functional_runner && ./tests/acceptance_runner"
