GigaReviewTest:
  variables:
    COMPOSE_FILE: docker-compose.yml
    REPO_NAME: $CI_PROJECT_NAME
    REVIEW_ENV: dev
    POSTGRES_MAJOR_VERSION: 12
    GROUP_VARIABLES_URL: "https://gitlab.com/api/v4/groups/gigascience/variables?per_page=100"
    FORK_VARIABLES_URL: "https://gitlab.com/api/v4/groups/3501869/variables"
    PROJECT_VARIABLES_URL: "https://gitlab.com/api/v4/projects/gigascience%2Fforks%2F$REPO_NAME/variables"
    MISC_VARIABLES_URL: "https://gitlab.com/api/v4/projects/gigascience%2Fcnhk-infra/variables"
  stage: test
  script:
    - env | grep -iE "(REVIEW_ENV|REPO_NAME|POSTGRES_MAJOR_VERSION|POSTGRES_DB|POSTGRES_USER|POSTGRES_PASSWORD|GROUP_VARIABLES_URL|FORK_VARIABLES_URL|PROJECT_VARIABLES_URL|MISC_VARIABLES_URL|GITLAB_PRIVATE_TOKEN)"| tee gigareview/.env
    - cd gigareview
    - ./up.sh
    - "./tests/unit_runner && ./tests/functional_runner && ./tests/acceptance_runner"
  environment:
    name: dev
  artifacts:
    paths:
      - gigareview/.env
      - gigareview/.secrets
      - gigareview/environments
      - .env
      - .secrets
      - .ci_env
    when: always
    expire_in: 1 week