GigaReviewTest:
  stage: test
  script:
    - cd gigareview
    - echo "GITLAB_PRIVATE_TOKEN=$GITLAB_PRIVATE_TOKEN" > .env
    - echo "REPO_NAME=$CI_PROJECT_NAME" >> .env
    - ./up.sh
    - "./tests/unit_runner && ./tests/functional_runner && ./tests/acceptance_runner"
