PureFtpdDeployStaging:
  stage: staging deploy
  variables:
    GIGADB_ENV: staging
    REMOTE_FILESERVER_DOCKER: "$remote_files_public_ip:2376"
  script:
    # Deployment to bastion server
    - mkdir -pv ~/.docker
    - bash -c "echo '$docker_fileserver_tlsauth_ca' >  ~/.docker/ca.pem"
    - bash -c "echo '$docker_fileserver_tlsauth_cert' > ~/.docker/cert.pem"
    - bash -c "echo '$docker_fileserver_tlsauth_key' > ~/.docker/key.pem"
    - echo "$GIGADB_ENV"
    - echo "$REMOTE_FILESERVER_DOCKER"
    - docker --tlsverify -H=$REMOTE_FILESERVER_DOCKER info
    - docker --tlsverify -H=$REMOTE_FILESERVER_DOCKER login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker --tlsverify -H=$REMOTE_FILESERVER_DOCKER pull registry.gitlab.com/$CI_PROJECT_PATH/production_ftpd:$GIGADB_ENV
  environment:
    name: $GIGADB_ENV
  dependencies: []
  needs: [ "PureFtpdBuildStaging" ]
  artifacts:
    untracked: true
    when: always
    expire_in: 1 week
