version: '3.7'
services:
  production_xls_uploader:
    build:
      context: .
      dockerfile: Dockerfile-Production

  production_pgclient:
    environment:
      PGDATABASE: ${gigadb_db_database}
      PGHOST: ${gigadb_db_host}
      PGPORT: ${gigadb_db_port}
      PGUSER: ${gigadb_db_user}
      PGPASSWORD: ${gigadb_db_password}
    build:
      context: .
      dockerfile: PgClientDockerfile