version: '3.7'
services:
  console:
    build:
      context: .
    working_dir: /gigadb/app/tools/files-metadata-console
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/gigadb/app/tools/files-metadata-console:delegated
      - ../../services:/gigadb/app/services
      - ../../models:/gigadb/app/models
    ports:
      - '8000:80'
    networks:
      # Connect to db-tier network in ops/docker-compose.yml
      - proxy-db-tier

  composer:
    environment:
      DOCKER_RUNNING: "true"
    image: composer/composer:2.4.4
    working_dir: /gigadb/app/tools/files-metadata-console
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/gigadb/app/tools/files-metadata-console:delegated
      - ../../services:/gigadb/app/services
      - ../../models:/gigadb/app/models


networks:
  proxy-db-tier:  # represents db-tier network in ops/docker-compose.yml
    name: deployment_db-tier