FilesMetaDataConsoleDeployStaging:
  stage: staging deploy
  variables:
    GIGADB_ENV: staging
    REMOTE_WEBAPP_DOCKER: "$remote_public_ip:2376"
    REMOTE_BASTION_DOCKER: "$remote_bastion_public_ip:2376"
  script:
    # Deployment to bastion server
    - mkdir -pv ~/.docker
    - bash -c "echo '$docker_bastion_tlsauth_ca' >  ~/.docker/ca.pem"
    - bash -c "echo '$docker_bastion_tlsauth_cert' > ~/.docker/cert.pem"
    - bash -c "echo '$docker_bastion_tlsauth_key' > ~/.docker/key.pem"
    - docker --tlsverify -H=$REMOTE_BASTION_DOCKER info
    - docker --tlsverify -H=$REMOTE_BASTION_DOCKER login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker --tlsverify -H=$REMOTE_BASTION_DOCKER pull registry.gitlab.com/$CI_PROJECT_PATH/production-files-metadata-console:latest
  environment:
    name: $GIGADB_ENV
  dependencies: []
  needs: [ "FilesMetadataConsoleBuildStaging" ]
  artifacts:
    untracked: true
    paths:
      - php-$PHP_VERSION-fpm-buster.tar
      - php-$PHP_VERSION-cli-buster.tar
      - php-8.2.3-cli-bullseye.tar
      - alpine-3_14.tar
      - nginx-$NGINX_VERSION-alpine.tar
      - node-$NODE_VERSION-buster-slim.tar
    when: always
    expire_in: 1 week