version: '3.7'
services:

  production_tool:
    build:
      context: ../../../..
      dockerfile: gigadb/app/tools/readme-generator/Dockerfile-Production
      cache_from:
        - "registry.gitlab.com/$CI_PROJECT_PATH/production_tool:$GIGADB_ENV"

  config:
    image: rija/docker-alpine-shell-tools:1.0.1
    volumes:
      - .:/app
    command: /app/generate_config.sh
