- name: copy the private ip address to GITLAB CI environment variable (first time)
  delegate_to: localhost
  uri:
    url: "{{ gitlab_url }}/variables"
    method: POST
    headers:
      PRIVATE-TOKEN: "{{ gitlab_private_token }}"
      # Content-Type: application/x-www-form-urlencoded
    body_format: json
    body:
      key: "remote{{ target_host }}_private_ip"
      value: "{{ private_ip }}"
      environment_scope: "{{ gigadb_environment }}"
    status_code:
      - 201
      - 400
  register: private_ip_post_outcome

- name: copy the private ip address to GITLAB CI environment variable (subsequently)
  delegate_to: localhost
  uri:
    url: "{{ gitlab_url }}/variables/remote{{ target_host }}_private_ip?filter%5benvironment_scope%5d={{ gigadb_environment }}"
    method: PUT
    headers:
      PRIVATE-TOKEN: "{{ gitlab_private_token }}"
    body_format: json
    body:
      value: "{{ private_ip }}"
    status_code: 200
  register: private_ip_put_outcome
  when: private_ip_post_outcome.status == 400

- name: copy the public ip address to GITLAB CI environment variable (first time)
  delegate_to: localhost
  uri:
    url: "{{ gitlab_url }}/variables"
    method: POST
    headers:
      PRIVATE-TOKEN: "{{ gitlab_private_token }}"
      # Content-Type: application/x-www-form-urlencoded
    body_format: json
    body:
      key: "remote{{ target_host }}_public_ip"
      value: "{{ public_ip }}"
      environment_scope: "{{ gigadb_environment }}"
    status_code:
      - 201
      - 400
  register: public_ip_post_outcome

- name: copy the public ip address to GITLAB CI environment variable (subsequently)
  delegate_to: localhost
  uri:
    url: "{{ gitlab_url }}/variables/remote{{ target_host }}_public_ip?filter%5benvironment_scope%5d={{ gigadb_environment }}"
    method: PUT
    headers:
      PRIVATE-TOKEN: "{{ gitlab_private_token }}"
    body_format: json
    body:
      value: "{{ public_ip }}"
    status_code: 200
  register: public_ip_put_outcome
  when: public_ip_post_outcome.status == 400
