version: '3.7'
services:
  pg9_3:
    build:
      context: .
      dockerfile: LegacyPgDockerfile
    ports:
      - '5432:5432'

  updater:
    build:
      context: .
    volumes:
      - .:/app
      - .:/logs
      - ./sql:/downloads


  config:
    image: rija/docker-alpine-shell-tools:1.0.1
    volumes:
      - .:/app
    command: /app/generate_config.sh