version: '3.7'
services:

  production_s3backup:
    build:
      context: .
      dockerfile: S3BackupDockerfile
      cache_from:
        - "registry.gitlab.com/$CI_PROJECT_PATH/production_s3backup:$GIGADB_ENV"


  production_updater:
    build:
      context: .
      dockerfile: Dockerfile-Production
      cache_from:
        - "registry.gitlab.com/$CI_PROJECT_PATH/production_updater:$GIGADB_ENV"

  config:
    image: rija/docker-alpine-shell-tools:1.0.1
    volumes:
      - .:/app
    command: /app/generate_config.sh


  production_pg9_3:
    build:
      context: .
      dockerfile: LegacyPgDockerfile
      cache_from:
        - "registry.gitlab.com/$CI_PROJECT_PATH/production_pg9_3:$GIGADB_ENV"
    ports:
      - '5432:5432'