
FilesUrlsUpdaterTest:
  variables:
    LOCAL_COMPOSE: "docker-compose -f ./docker-compose.yml"
    GIGADB_HOST: "172.17.0.1"
    GIGADB_PASSWORD: ""
    GIGADB_ENV: dev
    MISC_VARIABLES_URL: "https://gitlab.com/api/v4/projects/gigascience%2Fcnhk-infra/variables"
    FOO: "bar"
  stage: test
  artifacts:
    paths:
      - gigadb/app/tools/files-url-updater/runtime/logs/app.log
      - gigadb/app/tools/files-url-updater/tests/_output
      - gigadb/app/tools/files-url-updater/drop_restore.log
      - gigadb/app/tools/files-url-updater/config/params.php
      - gigadb/app/tools/files-url-updater/composer.json
      - gigadb/app/tools/files-url-updater/composer.lock
      - gigadb/app/tools/files-url-updater/tests/acceptance.suite.yml
      - gigadb/app/tools/files-url-updater/tests/ci.acceptance.suite.yml
      - gigadb/app/tools/files-url-updater/.env
      - gigadb/app/tools/files-url-updater/.secrets
      - .env
      - .secrets
      - protected/config/db.json
    when: always
    expire_in: 1 week
  script:
    - env | grep -iE "(GIGADB_ENV|MISC_VARIABLES_URL|GITLAB_PRIVATE_TOKEN)"| tee gigadb/app/tools/files-url-updater/.env
    - cd gigadb/app/tools/files-url-updater
    - $LOCAL_COMPOSE run --rm config
    - $LOCAL_COMPOSE run --rm updater composer install
    - $LOCAL_COMPOSE up -d pg9_3
    - echo yes | $LOCAL_COMPOSE run --rm updater ./yii dataset-files/download-restore-backup --default
    - $LOCAL_COMPOSE run --rm updater ./vendor/bin/codecept build
    - sleep 5
    - $LOCAL_COMPOSE ps
    - $LOCAL_COMPOSE run --rm updater ./vendor/bin/codecept run tests/unit
    - $LOCAL_COMPOSE run --rm updater ./vendor/bin/codecept run tests/functional
  needs: ["container_scanning","phpcs-security-audit-sast"]
  environment:
    name: dev

FilesUrlsUpdaterBuildStaging:
  stage: staging build
  variables:
    LOCAL_COMPOSE: "docker-compose -f ./docker-compose.production.yml"
    REPO_NAME: $CI_PROJECT_NAME
    GIGADB_ENV: staging
    GROUP_VARIABLES_URL: "https://gitlab.com/api/v4/groups/gigascience/variables?per_page=100"
    FORK_VARIABLES_URL: "https://gitlab.com/api/v4/groups/3501869/variables"
    PROJECT_VARIABLES_URL: "https://gitlab.com/api/v4/projects/gigascience%2Fforks%2F$REPO_NAME/variables"
    MISC_VARIABLES_URL: "https://gitlab.com/api/v4/projects/gigascience%2Fcnhk-infra/variables"
  script:
    - env | grep -iE "(GIGADB_ENV|MISC_VARIABLES_URL|GITLAB_PRIVATE_TOKEN)"| tee gigadb/app/tools/files-url-updater/.env
    - cd gigadb/app/tools/files-url-updater
    - $LOCAL_COMPOSE run --rm config #run generate_config to create configuration file with variables from staging
    - $LOCAL_COMPOSE build production_updater # build production container from the production docker file
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com # log in to Gitlab so we can push the container image there
    - docker tag ${CI_PROJECT_NAME}_production_updater:latest registry.gitlab.com/$CI_PROJECT_PATH/production_updater:$GIGADB_ENV
    - docker push registry.gitlab.com/$CI_PROJECT_PATH/production_updater:$GIGADB_ENV
  dependencies: []
  environment:
    name: staging
  artifacts:
    paths:
      - gigareview/.env
      - gigareview/.secrets
      - gigareview/environments
      - gigareview/console/config
      - gigareview/common/config
      - .env
      - .secrets
      - .ci_env
    when: always
    expire_in: 3 days
    needs: ["FilesUrlsUpdaterTest"]