- debug: msg="{{ newuser }}"

- name: Add curator user
  ansible.builtin.user:
    name: "{{ newuser }}"
    shell: /bin/bash
    groups: centos
    append: yes

- name: Create a .ssh and uploadDir directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ newuser }}"
    group: "{{ newuser }}"
    mode: '0700'
  loop:
    - "/home/{{ newuser }}/.ssh"
    - "/home/{{ newuser }}/uploadDir"

- name: Create directory to store keys
  ansible.builtin.file:
    path: "/home/centos/{{ newuser }}.keys"
    state: directory
    owner: centos
    group: centos


- name: generate private/public key pair
  community.crypto.openssh_keypair:
    path: "/home/centos/{{ newuser }}.keys/id_ssh_rsa"
    owner: centos
  register: pk


- name: Add curator to sudoers
  ansible.builtin.copy:
    content: "{{ newuser }} ALL=(ALL)       NOPASSWD: /home/centos/datasetUpload.sh, /home/centos/postUpload.sh\n"
    dest: "/etc/sudoers.d/91-add-{{ newuser }}"
    owner: root
    group: root
    mode: 440

- name: Add public key to authorized keys
  ansible.builtin.copy:
    content: "{{ pk.public_key }}"
    dest: "/home/{{ newuser }}/.ssh/authorized_keys"
    owner: "{{ newuser }}"
    group: "{{ newuser }}"
    mode: g-rw,o-rw

- name: Restart systemd sshd service
  command: systemctl restart sshd.service