---
# Deploy monitoring on an ec2 instance

- name: Install node exporter
  hosts: monitoring_hosts
  roles:
    - prometheus.prometheus.node_exporter

- name: Install Prometheus
  hosts: monitoring_hosts
  roles:
    - prometheus.prometheus.prometheus
  vars:
    prometheus_targets:
      node:
        - targets:
            - localhost:9100
          labels:
            env: gigascience-monitoring

- name: Install Grafana
  hosts: monitoring_hosts
  roles:
    - ansible-grafana

- name: Configure Grafana
  hosts: monitoring_hosts
  collections:
    - community.grafana

  module_defaults:
    group/community.grafana.grafana:
      grafana_url: "http://localhost:3000"
      grafana_user: "admin"
      grafana_password: "admin"

  tasks:
    - name: Ensure Prometheus datasource exists.
      grafana_datasource:
        grafana_url: "http://localhost:3000"
        grafana_user: "admin"
        grafana_password: "admin"
        name: "datasource-prometheus"
        ds_type: "prometheus"
        ds_url: "http://localhost:9090"
        access: "proxy"
        validate_certs: "false"
        tls_skip_verify: "true"
        uid: gigascience-prometheus-datasource
        state: present
      register: datasource

    - debug:
        msg: "datasource output: {{ datasource }}"

    - name: Import Prometheus Grafana dashboard
      grafana_dashboard:
        dashboard_url: https://s3.ap-northeast-1.wasabisys.com/gigadb-monitoring-resources/node-exporter-full_rev31.json
        overwrite: true
