version: '3.7'

services:

  config:
    image: rija/docker-alpine-shell-tools:1.0.1
    volumes:
      - ./:/app
    command: /app/generate_config.sh

  rclone:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config:/root/.config/rclone
      - .:/app

  rclone_cngb:
    image: rclone:cngb
    volumes:
      - ./config:/root/.config/rclone
      - .:/app
      - /data/gigadb/pub/10.5524/:/live-data/gigadb/pub/10.5524/:ro
    environment:
      HOST_HOSTNAME: "cngb-gigadb-bak"

  swatchdog:
    build:
      context: .
      dockerfile: Swatchdog-Dockerfile
    volumes:
      - .:/app
    command: swatchdog -c /app/config/swatchdog.conf -t "/app/logs/rclone_latest.log"

  swatchdog_cngb:
    image: swatchdog:cngb
    volumes:
      - .:/app
    environment:
      HOST_HOSTNAME: "cngb-gigadb-bak"
    command: swatchdog -c /app/config/swatchdog.conf -t "/app/logs/rclone_latest.log"
