version: '3.7'

services:

  config:
    image: rija/docker-alpine-shell-tools:1.0.1
    volumes:
      - ./:/app
    command: /app/generate_config.sh

  rclone:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config:/root/.config/rclone
      - .:/app

  swatchdog:
    build:
      context: .
      dockerfile: Swatchdog-Dockerfile
    volumes:
      - .:/app
    command: /bin/bash spinup_swatchdog_daemon.sh


  rclone_cngb:
    image: rclone:cngb
    volumes:
      - ./config:/root/.config/rclone
      - .:/app
      - /data/gigadb/pub/10.5524/:/live-data/gigadb/pub/10.5524/:ro
